USE [master]
GO
/****** Object:  Database [CommandsDB]    Script Date: 2021-03-14 23:42:02 ******/
CREATE DATABASE [CommandsDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CommandsDB', FILENAME = N'/var/opt/mssql/data/CommandsDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CommandsDB_log', FILENAME = N'/var/opt/mssql/data/CommandsDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [CommandsDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CommandsDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [CommandsDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CommandsDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CommandsDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CommandsDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CommandsDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [CommandsDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [CommandsDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CommandsDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CommandsDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CommandsDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CommandsDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CommandsDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CommandsDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CommandsDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CommandsDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [CommandsDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CommandsDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CommandsDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CommandsDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CommandsDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CommandsDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CommandsDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CommandsDB] SET RECOVERY FULL 
GO
ALTER DATABASE [CommandsDB] SET  MULTI_USER 
GO
ALTER DATABASE [CommandsDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CommandsDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CommandsDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CommandsDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [CommandsDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [CommandsDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'CommandsDB', N'ON'
GO
ALTER DATABASE [CommandsDB] SET QUERY_STORE = OFF
GO
USE [CommandsDB]
GO
/****** Object:  Table [dbo].[Commands]    Script Date: 2021-03-14 23:42:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Commands](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[HowTo] [nvarchar](200) NULL,
	[CommandLine] [nvarchar](50) NOT NULL,
	[PlatformId] [int] NOT NULL,
 CONSTRAINT [PK_Commands] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Platforms]    Script Date: 2021-03-14 23:42:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Platforms](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[LicenseKey] [nvarchar](50) NULL,
 CONSTRAINT [PK_Platforms] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [PlatformName] UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Commands]  WITH CHECK ADD  CONSTRAINT [FK_Commands_Platforms] FOREIGN KEY([PlatformId])
REFERENCES [dbo].[Platforms] ([Id])
GO
ALTER TABLE [dbo].[Commands] CHECK CONSTRAINT [FK_Commands_Platforms]
GO
USE [master]
GO
ALTER DATABASE [CommandsDB] SET  READ_WRITE 
GO
